controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    front_left_position_controller:
      type: position_controllers/JointGroupPositionController

    front_left_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    front_left_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    front_right_position_controller:
      type: position_controllers/JointGroupPositionController

    front_right_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    front_right_effort_controller:
      type: effort_controllers/JointGroupEffortController

    back_left_position_controller:
      type: position_controllers/JointGroupPositionController

    back_left_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    back_left_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    back_right_position_controller:
      type: position_controllers/JointGroupPositionController

    back_right_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    back_right_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    group_position_controller:
      type: position_controllers/JointGroupPositionController

    group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    group_effort_controller:
      type: effort_controllers/JointGroupEffortController

front_left_position_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint

front_left_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint

front_left_effort_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint

front_right_position_controller:
  ros__parameters:
    joints:
      - front_right_wheel_joint

front_right_velocity_controller:
  ros__parameters:
    joints:
      - front_right_wheel_joint

front_right_effort_controller:
  ros__parameters:
    joints:
      - front_right_wheel_joint

back_left_position_controller:
  ros__parameters:
    joints:
      - back_left_wheel_joint

back_left_velocity_controller:
  ros__parameters:
    joints:
      - back_left_wheel_joint

back_left_effort_controller:
  ros__parameters:
    joints:
      - back_left_wheel_joint

back_right_position_controller:
  ros__parameters:
    joints:
      - back_right_wheel_joint

back_right_velocity_controller:
  ros__parameters:
    joints:
      - back_right_wheel_joint

back_right_effort_controller:
  ros__parameters:
    joints:
      - back_right_wheel_joint

group_position_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - back_left_wheel_joint
      - back_right_wheel_joint

group_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - back_left_wheel_joint
      - back_right_wheel_joint

group_effort_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - back_left_wheel_joint
      - back_right_wheel_joint
